services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: docker/Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/App
    depends_on:
      - database
